refactor: update github actions

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -23,23 +23,8 @@ jobs:
 
     steps:
       - uses: actions/checkout@v3
-        id: pr_info
         with:
           lfs: true
-          github-token: ${{secrets.GITHUB_TOKEN}}
-          script: |
-            const { data: pull_requests } = await github.pulls.list({
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              head: context.repo.owner + ":" + context.sha
-            });
-            if (pull_requests.length > 0 && pull_requests[0].hasOwnProperty('html_url')) {
-              return pull_requests[0].html_url;
-            }
-            return '';
-      - name: Set PR html_url
-        run: echo "PR_URL=${{ steps.pr_info.outputs.result }}" >> $GITHUB_ENV
-
       - name: Use Node.js ${{ matrix.node-version }}
         uses: actions/setup-node@v3
         with:
@@ -65,9 +50,17 @@ jobs:
           NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           NODE_OPTIONS: '--max_old_space_size=4096'
         run: |
+          set +e  # don't stop on errors
           npm i -g expo-cli@6.0.8 && yarn --mode=skip-build && yarn patch-package
           yarn lint
-
+          echo "LINT_EXIT_CODE=$?" >> $GITHUB_ENV  # store the exit code for use in subsequent steps
+        shell: bash
+      - name: Extract Pull Request Number
+        id: pr_number
+        run: echo "PR_NUMBER=$(echo $GITHUB_REF | awk -F '/' '{print $3}')" >> $GITHUB_ENV
+      - name: Form Pull Request URL
+        id: pr_url
+        run: echo "PR_URL=https://github.com/$GITHUB_REPOSITORY/pull/$PR_NUMBER" >> $GITHUB_ENV
       - name: Get Date
         id: date
         run: echo "DATE=$(date -u +'%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_ENV
@@ -85,4 +78,5 @@ jobs:
             
             See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
             Pull Request: ${{ env.PR_URL }}
+            Lint Exit Code: ${{ env.LINT_EXIT_CODE }}  # report the exit code of the lint step
 
